### ISSUE TITLE
Execution is halted if a Hook with no name is provided

### ISSUE THREAD

**Issue by noxdafox** [F-Secure/see#20]
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sandbox/task_manager.py", line 38, in process_task
    self.execute_task(task, results_path)
  File "/usr/lib/python3/dist-packages/sandbox/task_manager.py", line 58, in execute_task
    run_sandbox(parameters)
  File "/usr/lib/python3/dist-packages/sandbox/sandbox.py", line 38, in run_sandbox
    identifier=parameters.identifier) as environment:
  File "/usr/local/lib/python3.4/dist-packages/see/environment.py", line 59, in __enter__
    self.allocate()
  File "/usr/local/lib/python3.4/dist-packages/see/environment.py", line 80, in allocate
    self._allocate()
  File "/usr/local/lib/python3.4/dist-packages/see/environment.py", line 88, in _allocate
    self._context)
  File "/usr/local/lib/python3.4/dist-packages/see/hooks.py", line 33, in hooks_factory
    manager.load_hooks(context)
  File "/usr/local/lib/python3.4/dist-packages/see/hooks.py", line 55, in load_hooks
    self._load_hook(hook['name'], config, context)
KeyError: 'name'
```

It would probably be better to report the problematic Hook and continue the execution.

**Comment by noxdafox** [comment]
Issue resolved  by submitted patch.
