### ISSUE TITLE
AttributeError when accessing uninitialized resources

### ISSUE THREAD

**Issue by noxdafox** [F-Secure/see#38]
If the User will not generate a network or a storage pool and will try to access it he/she will get a misleading AttributeError.

```
Traceback (most recent call last):
  File "execute_sample.py", line 66, in <module>
    main()
  File "execute_sample.py", line 20, in main
    protocol(environment.context, arguments.sample, arguments.command)
  File "execute_sample.py", line 26, in protocol
    wait_for_ip_address(context, TIMEOUT)
  File "execute_sample.py", line 44, in wait_for_ip_address
    if context.ip4_address is not None:
  File "/usr/local/lib/python3.4/dist-packages/see/context/context.py", line 193, in ip4_address
    if self._ip4_address is None and self.network is not None:
  File "/usr/local/lib/python3.4/dist-packages/see/context/context.py", line 161, in network
    if self._resources.network.isActive():
AttributeError: 'NoneType' object has no attribute 'isActive'
```

As well, the Tutorial does not mention the network in the context.json file.

**Comment by noxdafox** [comment]
fixed in 1.2.3
